---
title: "О единорогах и временных рядах"
output: html_document
editor_options:
  chunk_output_type: console
---

* [Видео-лекции](https://www.youtube.com/watch?v=fMLLt9cywAw&list=PLJaoagXyJROgy5wPOZcBoP1aOK6XXOpjz)
* Прототип [задачника по рядам](https://github.com/bdemeshev/ts_pset/raw/master/ts_pset_main.pdf). Полностью наш, отечественный продукт :)

## Встреча 1

1. ETS-модели

2. LOESS-регрессия

3. STL-разложение


* Кратко [про всё сразу](https://robjhyndman.com/files/2-AutomaticForecasting.pdf)
* Все [ETS-модели](https://otexts.org/fpp2/ets.html)
* Оригинальная [статья Кливленда](http://www.wessa.net/download/stl.pdf) про STL
* STL пример, [часть 1](http://www.gardner.fyi/blog/STL-Part-I/) и [часть 2](http://www.gardner.fyi/blog/STL-Part-II/)


Весь код для loess:
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
qplot(data = trees, x = Girth, y = Height) + stat_smooth(method = "loess", span = 1)
```



## Встреча 2

1. ARIMA



## Встреча 3

1. Разница TBATS - ETS

2. Тригонометрическое моделирование сезонности

3. Модели состояние наблюдения

4. Фильтр Калмана: легкая половина



* Смысл непрерывного [преобразования Фурье](https://www.youtube.com/watch?v=spUNpyF58BY) от 3blue1brown
* Walter Lewin [Fourier Analysis, Time evolution of Pulses on Strings](https://www.youtube.com/watch?v=k3byqIaULb8)
* Пакет [prophet](https://facebook.github.io/prophet/) от Фейсбука
* Статья [tbats](https://robjhyndman.com/papers/ComplexSeasonality.pdf)
* Виньетка [пакета glm](https://cran.r-project.org/web/packages/dlm/vignettes/dlm.pdf)


* Aad den Vaart, [курс по временным рядам](http://www.math.leidenuniv.nl/~avdvaart/timeseries/dictaat.pdf). Очень кратко, но очень удачно изложен фильтр Калмана.
* Decrouez, [Stochastic modelling](https://cs.hse.ru/ai/sm): Очень подробно и красивым почерком изложен фильтр Калмана. К слову, у Декруэ есть не менее шикарные [Modern methods of decision making](https://cs.hse.ru/ai/mmdm), [Probability theory](https://cs.hse.ru/ai/ptms).
* Pollock, [Лекции по рядам](https://www.le.ac.uk/users/dsgp1/COURSES/TSERIES/PROSERIE.HTM). Нам актуальна лекция Seasons and cycles.

## Не успел, но очень хотел:

- полностью вывод фильтра Калмана
- FASSTER
- PROPHET

* Презентация [FASSTER](http://www.mitchelloharawild.com/melburn17/#1)
